version: "3.7"

services:

    acronis-server:
        container_name: acronis-server
        build:
            context: ../
            dockerfile: docker/GoLang/Dockerfile.dev
        volumes:
            - ./../server:/go/src
            - ./../fixtures:/usr/share/files
        command: fresh
        ports:
            - "127.0.77.1:80:8080"

    acronis-client:
        container_name: acronis-client
        build:
            context: ../
            dockerfile: docker/GoLang/Dockerfile.dev
        volumes:
            - ./../client:/go/src
        environment:
            - APP_ENV=dev
        command: fresh
        depends_on:
            - acronis-server