version: "3.7"

networks:
    default:
        name: "acronis"
        ipam:
            driver: default

services:

    acronis-server:
        container_name: acronis-server
        build:
            context: ../
            dockerfile: docker/GoLang/Dockerfile.dev
        volumes:
            - ./../server:/go/src
            - ./../fixtures:/usr/share/files:ro
        command: fresh
        ports:
            - "127.0.77.1:80:8080"

    acronis-client:
        container_name: acronis-client
        build:
            context: ../
            dockerfile: docker/GoLang/Dockerfile.dev
        volumes:
            - ./../client:/go/src
            - ./../downloads:/usr/share/downloads
        environment:
            - FILE_SERVER_URL=http://acronis-server:8080
        command: fresh
        depends_on:
            - acronis-server